require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ServicosController do

  # This should return the minimal set of attributes required to create a valid
  # Servico. As you add validations to Servico, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ServicosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all servicos as @servicos" do
      servico = Servico.create! valid_attributes
      get :index, {}, valid_session
      assigns(:servicos).should eq([servico])
    end
  end

  describe "GET show" do
    it "assigns the requested servico as @servico" do
      servico = Servico.create! valid_attributes
      get :show, {:id => servico.to_param}, valid_session
      assigns(:servico).should eq(servico)
    end
  end

  describe "GET new" do
    it "assigns a new servico as @servico" do
      get :new, {}, valid_session
      assigns(:servico).should be_a_new(Servico)
    end
  end

  describe "GET edit" do
    it "assigns the requested servico as @servico" do
      servico = Servico.create! valid_attributes
      get :edit, {:id => servico.to_param}, valid_session
      assigns(:servico).should eq(servico)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Servico" do
        expect {
          post :create, {:servico => valid_attributes}, valid_session
        }.to change(Servico, :count).by(1)
      end

      it "assigns a newly created servico as @servico" do
        post :create, {:servico => valid_attributes}, valid_session
        assigns(:servico).should be_a(Servico)
        assigns(:servico).should be_persisted
      end

      it "redirects to the created servico" do
        post :create, {:servico => valid_attributes}, valid_session
        response.should redirect_to(Servico.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved servico as @servico" do
        # Trigger the behavior that occurs when invalid params are submitted
        Servico.any_instance.stub(:save).and_return(false)
        post :create, {:servico => {}}, valid_session
        assigns(:servico).should be_a_new(Servico)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Servico.any_instance.stub(:save).and_return(false)
        post :create, {:servico => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested servico" do
        servico = Servico.create! valid_attributes
        # Assuming there are no other servicos in the database, this
        # specifies that the Servico created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Servico.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => servico.to_param, :servico => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested servico as @servico" do
        servico = Servico.create! valid_attributes
        put :update, {:id => servico.to_param, :servico => valid_attributes}, valid_session
        assigns(:servico).should eq(servico)
      end

      it "redirects to the servico" do
        servico = Servico.create! valid_attributes
        put :update, {:id => servico.to_param, :servico => valid_attributes}, valid_session
        response.should redirect_to(servico)
      end
    end

    describe "with invalid params" do
      it "assigns the servico as @servico" do
        servico = Servico.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Servico.any_instance.stub(:save).and_return(false)
        put :update, {:id => servico.to_param, :servico => {}}, valid_session
        assigns(:servico).should eq(servico)
      end

      it "re-renders the 'edit' template" do
        servico = Servico.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Servico.any_instance.stub(:save).and_return(false)
        put :update, {:id => servico.to_param, :servico => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested servico" do
      servico = Servico.create! valid_attributes
      expect {
        delete :destroy, {:id => servico.to_param}, valid_session
      }.to change(Servico, :count).by(-1)
    end

    it "redirects to the servicos list" do
      servico = Servico.create! valid_attributes
      delete :destroy, {:id => servico.to_param}, valid_session
      response.should redirect_to(servicos_url)
    end
  end

end
